[project]
name = "api"
version = "0.1.0"
description = "Designing API as a backend for watches store."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.0",
    "uvicorn>=0.38.0",
]
